### ISSUE TITLE
Support for boolean values

### ISSUE THREAD

**Issue by git-developer** [ddtlabs/expandJSON#1]
The module doesn't create readings for boolean values. For example:
`{ "timestamp":1496588366, "sensor_id":"5157", "temperature":23.8, "humidity":59, "lowbat":true, "rssi":79 }`
The module creates readings for all values but `lowbat`. I suppose this is because boolean values have no surrounding quotes in JSON and perl doesn't have a boolean type.

**Comment by ddtlabs** [comment]
Should already be fixed in FHEM repository. Use FHEM's update feature, please.
