### ISSUE TITLE
Treatment of special characters

### ISSUE THREAD

**Issue by git-developer** [ddtlabs/expandJSON#2]
Special characters like German Umlauts (ä, ö, ü) are not properly decoded to Perl strings. Example:
the JSON string `{ "demo-string":"aäoöuü" }` is translated into reading `demo-string` with value`a�o�u�`. This happens because the used function `json_decode` applies a UTF-8 decode on the input string although Perl strings are already decoded.

**Comment by ddtlabs** [comment]
Should already be fixed in FHEM repository. Use FHEM's update feature, please.
